### PR TITLE
Fall 2023 Refactor

### PR DESCRIPTION
**Pull request by skhrg**
Fist pass at reorganizing and cleaning up minkasi.

Things to do in a later PR: 
* Refactor the fitting submodule
* More specific type hints. Right now I defaulted to not specifying the exact `dtype` for a lot of arrays (ie: `NDArray[np.floating]` instead of `NDArray[np.float64]`). At least the variables that eventually hit the C libraries should me more specific since we know when the C functions expect a double vs a float.
* Stuff from #14 

Before this is merged I want #15  merged into this branch.

Main thing I want feedback on is the splitting up of files. When I originally split up `minkasi.py` I was trying to get things into manageable length files (largely to I could chunk up this work easier). But its unclear to me if the current organization is optimal. 
Maybe there are too many top level files? One could imagine making a `mapmaking` submodule with `pcg`, `tod2map`, `map2tod`, and `noise`
Could also make a `utils` or `tools` submodule with things like `no_numba`, `parallel`, `pyregion_tools`, `smooth`, `zernike`, and `utils` (though that may need to be renamed in this case, `utils.utils` would be dumb...). 

Other thing that would be good to get input on is what functions/classes (if any) get to the top of the namespace in the root `__init__.py`.

### CODE REVIEW

**Comment by Sulla2012** [comment]
Some thoughts on Issues Found During Cleanup:

Regarding SkyMap, it looks like the needlet map making will also end up with its own very similar WavMap class, so at some point we should probably switch to inheriting from a base class. 

I noticed the tod2map_method thing as well: I cut it from the WavMap code and haven't noticed any issues yet. 

Agreed on builtin `map`. I think a naming scheme that is suggestive of the use of the map, like `imap` for input map, `wmap` for wavelett map, etc could be nice but this doesn't need to be done now. 

As for modifying tods in place, I agree about preferring pure functions however some of these are backended in C changing them all to be uniformly pure would be marginally more complicated.

 With respect to the reorganization, it looks amazing. I guess the only thing is, is it worth putting some of the "loose" files in folders? Was thinking maybe a mapmaking folder with pcg, tod2map/map2tod, and timestream? All in all amazing work

**Comment by skhrg** [comment]
> As for modifying tods in place, I agree about preferring pure functions however some of these are backended in C changing them all to be uniformly pure would be marginally more complicated.

I mean all the C functions work in place rn. But the python functions are inconsistent on what gets passed to them so that is where I think we should standardize the interface.

> With respect to the reorganization, it looks amazing. I guess the only thing is, is it worth putting some of the "loose" files in folders? Was thinking maybe a mapmaking folder with pcg, tod2map/map2tod, and timestream? All in all amazing work
Agreed. I think `noise` should be tossed in with these as well. 

Do you have thoughts on if/how the more generic tools like `zernike` and `smooth` should be organized? Also things that are mostly for internal use like `parallel` and `no_numba` (doubt anybody will import no_numba lol).

Related should MPI stuff like `comm` and `myrank` should be exposed in `__init__.py` since almost everything will use them?

**Comment by Sulla2012** [comment]
> I mean all the C functions work in place rn. But the python functions are inconsistent on what gets passed to them so that is where I think we should standardize the interface.

Ah I see. Agreed then.

>Do you have thoughts on if/how the more generic tools like zernike and smooth should be organized? Also things that are mostly for internal use like parallel and no_numba (doubt anybody will import no_numba lol).

Could just throw them in utils. The junk draw of the package

>Related should MPI stuff like comm and myrank should be exposed in __init__.py since almost everything will use them?

Yeah I think so

**Comment by skhrg** [comment]
Ok here are some proposals for moving things around.
At the very least we should do this:

```
.
├── code_scrapyard.py
├── fitting
│   ├── core.py
│   ├── __init__.py
│   ├── models.py
│   └── power_spectrum.py
├── __init__.py
├── mapmaking
│   ├── __init__.py
│   ├── map2tod.py
│   ├── noise.py
│   ├── pcg.py
│   ├── timestream.py
│   └── tod2map.py
├── maps
│   ├── __init__.py
│   ├── mapset.py
│   ├── polmap.py
│   ├── skymap.py
│   ├── twores.py
│   └── utils.py
├── minkasi_all.py
├── minkasi.c
├── minkasi.py
├── mkfftw.c
├── mkfftw.py
├── no_numba.py
├── parallel.py
├── pyregion_tools.py
├── smooth.py
├── tods
│   ├── core.py
│   ├── cuts.py
│   ├── _depracated.py
│   ├── __init__.py
│   ├── io.py
│   ├── processing.py
│   └── utils.py
└── utils.py
```
Mapmaking stuff is a submodule and `zernike` functions are tossed into `utils`

We can also do something like this:
```
.
├── code_scrapyard.py
├── fitting
│   ├── core.py
│   ├── __init__.py
│   ├── models.py
│   └── power_spectrum.py
├── __init__.py
├── lib
│   ├── minkasi.c
│   └── mkfftw.c
├── mapmaking
│   ├── __init__.py
│   ├── map2tod.py
│   ├── noise.py
│   ├── pcg.py
│   ├── timestream.py
│   └── tod2map.py
├── maps
│   ├── __init__.py
│   ├── mapset.py
│   ├── polmap.py
│   ├── skymap.py
│   ├── twores.py
│   └── utils.py
├── minkasi_all.py
├── minkasi.py
├── parallel.py
├── tods
│   ├── core.py
│   ├── cuts.py
│   ├── _depracated.py
│   ├── __init__.py
│   ├── io.py
│   ├── processing.py
│   └── utils.py
└── tools
    ├── __init__.py
    ├── mkfftw.py
    ├── no_numba.py
    ├── pyregion_tools.py
    ├── smooth.py
    └── utils.py

```
Where the more generically useful stuff goes into a `tools` submodule (maybe `parallel` belongs there?) and the c files go into their own folder.

Also would like to propose that we rename `code_scrapyard.py` to `_code_scrapyard.py` or `_scrapyard.py` to denote that its nor really supposed to be used.
Also maybe we rename `minkasi.py` to `libminkasi.py` to make it more clear that its just a wrapper for the library?

**Comment by skhrg** [comment]
Ok changed it to be like:
```.
├── fitting
│   ├── core.py
│   ├── __init__.py
│   ├── models.py
│   └── power_spectrum.py
├── __init__.py
├── lib
│   ├── __init__.py
│   ├── minkasi.c
│   ├── minkasi.py
│   ├── mkfftw.c
│   └── mkfftw.py
├── mapmaking
│   ├── __init__.py
│   ├── map2tod.py
│   ├── noise.py
│   ├── pcg.py
│   ├── timestream.py
│   └── tod2map.py
├── maps
│   ├── __init__.py
│   ├── mapset.py
│   ├── polmap.py
│   ├── skymap.py
│   ├── twores.py
│   └── utils.py
├── minkasi_all.py
├── parallel.py
├── _scrapyard.py
├── tods
│   ├── core.py
│   ├── cuts.py
│   ├── _depracated.py
│   ├── __init__.py
│   ├── io.py
│   ├── processing.py
│   └── utils.py
└── tools
    ├── array_ops.py
    ├── fft.py
    ├── __init__.py
    ├── no_numba.py
    ├── pyregion_tools.py
    ├── rings.py
    ├── smooth.py
    ├── units.py
    └── zernike.py
```
 Let me know if there are any objections.

**Pull request merged**
